runtime: python312 

entrypoint: gunicorn -b :$PORT myapp.wsgi

instance_class: F2

env_variables:
  DJANGO_SECRET_KEY: "MULdzAVreAkLpo7MPkjFoUt6ysd_cqY2GUTvECBGYdhJ_KZnTgPlgGTfAZAwadtFhiE"
  ALLOWED_HOSTS: ".appspot.com"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
